CREATE TABLE IF NOT EXISTS usuarios(
    ID INT AUTO_INCREMENT NOT NULL,
    NOMBRE VARCHAR(20) NOT NULL,
    APELLIDOS VARCHAR(60) NOT NULL,
    EDAD INT NOT NULL,
    SEXO VARCHAR(1) NOT NULL,
    PASSWORD VARCHAR(12) NOT NULL,
    ANIMEFAV VARCHAR(100),
    PRIMARY KEY(ID)
)ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS animes(
    ID INT AUTO_INCREMENT NOT NULL,
    NOMBRE VARCHAR(100) NOT NULL,
    GENERO VARCHAR(20) NOT NULL,
    LINK VARCHAR(500) NOT NULL,
    PRIMARY KEY (ID)
)ENGINE=INNODB;


